### ISSUE TITLE
Crash when dying in end void [BUG]

### ISSUE THREAD

**Issue by Desenrad** [haubna/PhysicsMod#1003]
**Describe the bug**
Every single time I die in the void. The game crashes and rolls back a few seconds.

**To Reproduce**
-Use Physics mod
-Die in void

**Screenshots**
Wont be helpful.

Minecraft Version: <version>
Physics Mod Version: <3.0.20>

Console output on crash:
```
[20:53:54] [Server thread/INFO]:
{MINECRAFT_USERNAME} fell out of the world
[20:53:54] [Render thread/INFO]:
[System] [CHAT] {MINECRAFT_USERNAME} fell out of the world
[20:53:54] [Render thread/ERROR]:
eINTERNAL_ERROR: QuickHullConvexHullLib::findSimplex: Simplex input points appers to be almost at the same place
[20:53:54] [Render thread/INFO]:
[STDERR]: java.lang.Exception: Stack trace
[20:53:54] [Render thread/INFO]:
[STDERR]: at java.base/java.lang.Thread.dumpStack(Unknown Source)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.StarterClient$1.reportError(StarterClient.java:230)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//physx.common.PxErrorCallbackImpl._reportError(PxErrorCallbackImpl.java:48)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//physx.PxTopLevelFunctions._CreateConvexMesh(Native Method)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//physx.PxTopLevelFunctions.CreateConvexMesh(PxTopLevelFunctions.java:287)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.ConvexRigidBody.create(ConvexRigidBody.java:146)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.PhysicsWorld.addBlockParticle(PhysicsWorld.java:1133)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.PhysicsWorld.addBlockParticle(PhysicsWorld.java:1179)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.ragdoll.BreakableRagdoll.add(BreakableRagdoll.java:63)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.physics.PhysicsWorld.addRagdoll(PhysicsWorld.java:1075)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.render.PhysicsUpdater.updatePhysics(PhysicsUpdater.java:288)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:162)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_761.handler$hpj000$physicsmod$renderMain(class_761.java:19681)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_761.method_3251(class_761.java:23770)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_761.method_22710(class_761.java:991)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_757.method_3188(class_757.java:1087)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_757.method_3192(class_757.java:850)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.class_310.method_1514(class_310.java:882)
[20:53:54] [Render thread/INFO]:
[STDERR]: at knot//net.minecraft.client.main.Main.main(Main.java:256)
[20:53:54] [Render thread/INFO]:
[STDERR]: at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[20:53:54] [Render thread/INFO]:
[STDERR]: at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:53:54] [Render thread/INFO]:
[STDERR]: at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:53:54] [Render thread/ERROR]:
Unable to Sync Container Data for a given Entity as it is null on the Client! [EntityId: 2]
```

**Comment by haubna** [comment]
I've just tried to reproduce this crash and was unable to do it. Do you use any other mods? Or I might have accidentally fixed this in the 1.21.4 version.

**Comment by Desenrad** [comment]
@haubna Hello,this crash occurred with my custom modpack. You can find the exported modpack file here.

http://gofile.me/6ZZ5k/MYEgEuMeV|
Maybe you will find some incompatibilities that could have caused this.

**Comment by ShayDeeJay** [comment]
Hi did this ever get solved? My mod pack is in 1.21.1 and i am getting this exact same issue

**Comment by minecraftuserthatwantsskins** [comment]
This is still an issue with the current 1.21.5 version where dying in the void causes the game to crash, and my version of the mod is from the official modrinth page.

**Comment by haubna** [comment]
Tried this several times but never  got a crash. Send me a proper crash log or the mod that causes this incompatibility (I am not installing your mod packs for obvious security reasons).
