### ISSUE TITLE
aether causing physics mod to lock up/crash [BUG]

### ISSUE THREAD

**Issue by Xplodin** [haubna/PhysicsMod#1009]
**Describe the bug**
going and killing things in the aether causes game to freeze, needing force closing
**To Reproduce**
Steps to reproduce the behavior.
have deep aether, aether, and physics mod

**Screenshots**

Minecraft Version: 1.20.1
Physics Mod Version: 171b forge

[net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
net.minecraft.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:111) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:66) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.handler$eml000$wrapAnimatableTexture(TextureManager.java:1529) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:741) ~[physics-mod-pro-v171b-forge-1.20.1.jar%23932!/:3.0.14]
	at net.minecraft.world.entity.LivingEntity.handler$ecn000$onDeath(LivingEntity.java:21057) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.world.entity.LivingEntity.m_7822_(LivingEntity.java:1732) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.world.entity.Mob.m_7822_(Mob.java:331) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7628_(ClientPacketListener.java:997) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.network.protocol.game.ClientboundEntityEventPacket.m_5797_(ClientboundEntityEventPacket.java:33) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.network.protocol.game.ClientboundEntityEventPacket.m_5797_(ClientboundEntityEventPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.m_135827_()" because "p_215482_" is null
	at net.minecraft.server.packs.resources.MultiPackResourceManager.m_213713_(MultiPackResourceManager.java:79) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_213713_(ReloadableResourceManager.java:49) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	at software.bernie.geckolib.cache.texture.AnimatableTexture.m_6704_(AnimatableTexture.java:40) ~[geckolib-forge-1.20.1-4.4.9.jar%23810!/:4.4.9]
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:96) ~[client-1.20.1-20230612.114412-srg.jar%231070!/:?]
	... 42 more

**Comment by Xplodin** [comment]
also happening in the End
