### ISSUE TITLE
Network Protocol Error after killing the ender dragon [BUG]

### ISSUE THREAD

**Issue by NeonBlaze101** [haubna/PhysicsMod#1014]
**Describe the bug**
After the ender dragon health reach 0 / after the ender dragon death animation finished, the player is kicked out of singleplayer world with message "Network Protocol Error"

**To Reproduce**
1. Load a singleplayer world
2. Go to the end
3. Kill the ender dragon manually (/data modify command doesn't trigger the bug)
4. The player is kicked out of the world with "Network Protocol Error"
5. Load that single player world again, wait until the dragon's death animation finished
6. The player is kicked out of the world with the same error. 

**Screenshots**
https://github.com/user-attachments/assets/001d3f79-db0b-4537-b67c-10b31b96c93f

Minecraft Version: 1.21.4
Physics Mod Version: 3.0.22

**Comment by NeonBlaze101** [comment]
Report file:[](url)
[disconnect-2024-12-06_23.51.53-client.txt](https://github.com/user-attachments/files/18041615/disconnect-2024-12-06_23.51.53-client.txt)

---- Minecraft Network Protocol Error Report ----
// Wait, was the last bit one or zero?

Time: 2024-12-06 23:51:53
Description: Packet handling error

java.lang.ClassCastException: class net.minecraft.class_895 cannot be cast to class net.minecraft.class_922 (net.minecraft.class_895 and net.minecraft.class_922 are in unnamed module of loader 'knot' @5d47c63f)
	at knot//net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:729)
	at knot//net.minecraft.class_1309.handler$znl000$physicsmod$onDeath(class_1309.java:5923)
	at knot//net.minecraft.class_1309.method_6078(class_1309.java)
	at knot//net.minecraft.class_1309.method_5711(class_1309.java:1952)
	at knot//net.minecraft.class_1308.method_5711(class_1308.java:360)
	at knot//net.minecraft.class_634.method_11148(class_634.java:1139)
	at knot//net.minecraft.class_2663.method_11471(class_2663.java:41)
	at knot//net.minecraft.class_2663.method_65081(class_2663.java:13)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:729)
	at knot//net.minecraft.class_1309.handler$znl000$physicsmod$onDeath(class_1309.java:5923)
	at knot//net.minecraft.class_1309.method_6078(class_1309.java)
	at knot//net.minecraft.class_1309.method_5711(class_1309.java:1952)
	at knot//net.minecraft.class_1308.method_5711(class_1308.java:360)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:entity_event
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:131)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:110)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Is Local: true
	Server type: <none>
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1042851096 bytes (994 MiB) / 1709178880 bytes (1630 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: Comet Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.1691
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 26.20.100.7985
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 25949.00
	Virtual memory used (MiB): 14107.95
	Swap memory total (MiB): 9728.00
	Swap memory used (MiB): 556.44
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 34851.15, total: 127968.00
	Space in storage for workdir (MiB): available: 103235.60, total: 283326.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.111.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.53+453d4f9104
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.84+7feeb73304
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.4+466a140b04
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.7+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.27+7feeb73304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.61+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.40+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.78+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.12+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.6+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.6+466a140b04
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.3+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.1.2+466a140b04
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.11+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.1+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.12+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.21+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.3+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.31+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.19+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.24+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.0+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.8+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.5+e604fe7f04
			fabric-particles-v1: Fabric Particles (v1) 4.0.13+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.3+fa62a02304
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.0.1+cc0fa2fe04
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.1+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.1+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.18+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.0+7e7568bf04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.10+203e6b2304
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.37+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.106+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.6+1885ad7404
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.4
		physicsmod: Physics Mod 3.0.22

**Comment by haubna** [comment]
Thank you for the report, I just uploaded 3.0.23 that fixes this issue.
