### ISSUE TITLE
Game crashes on occasion when tabbing in and out from the menu screen

### ISSUE THREAD

**Issue by TerdyTheTerd** [haubna/PhysicsMod#1020]
Sometimes when trying to tab back into the game it crashes with the following error pointing to the physics mod:
`Time: 2024-12-24 14:35:11
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_634.method_2871(java.util.UUID)" because the return value of "net.minecraft.class_310.method_1562()" is null
	at net.minecraft.class_742.method_3123(class_742.java:51)
	at net.minecraft.class_742.method_7325(class_742.java:38)
	at net.diebuddies.physics.PhysicsWorld.updateMinecraftEntities(PhysicsWorld.java:464)
	at net.diebuddies.physics.PhysicsWorld.physicsUpdate(PhysicsWorld.java:292)
	at net.diebuddies.physics.DynamicsWorld.update(DynamicsWorld.java:145)
	at net.diebuddies.physics.PhysicsWorld.update(PhysicsWorld.java:282)
	at net.minecraft.class_757.handler$dnd000$physicsmod$render(class_757.java:9239)
	at net.minecraft.class_757.method_3192(class_757.java)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

**Comment by haubna** [comment]
Which version were you using? This should be fixed in 1.21+.
