### ISSUE TITLE
The game just crashes when I use the mod log below

### ISSUE THREAD

**Issue by CeruleanDerpo** [haubna/PhysicsMod#12]
---- Minecraft Crash Report ----
// My bad.

Time: 13/07/21 12.01
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.entity.EntityRendererManager.handler$zzm000$register(EntityRendererManager.java:681) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229087_a_(EntityRendererManager.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:452) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.1.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/1327539680.call(Unknown Source) [forge-1.16.3-34.1.1.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.handler$zzm000$register(EntityRendererManager.java:681) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229087_a_(EntityRendererManager.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinEntityRenderDispatcher,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:452) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.1.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/1327539680.call(Unknown Source) [forge-1.16.3-34.1.1.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1165217016 bytes (1111 MB) / 1577058304 bytes (1504 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.1
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		[1.16.4]+SecurityCraft+v1.8.20.2.jar SecurityCraft {securitycraft@v1.8.20.2 NONE}
		backpacked-1.7.0-mc1.16.3.jar Backpacked {backpacked@1.7.0 NONE}
		backpacker-1.1.0-mc1.16.3.jar Backpacker {backpacker@1.1.0 NONE}
		cfm-7.0.0-pre19-mc1.16.3.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre19 NONE}
		chiselsandbits-0.3.4-RELEASE.jar Chisels & bits {chiselsandbits@NONE NONE}
		create-mc1.16.5_v0.3.1a.jar Create {create@mc1.16.5_v0.3.1a+128 NONE}
		immersive-portals-0.14-mc1.16.4-forge.jar Immersive Portals {immersive_portals@0.14 NONE}
		obfuscate-0.5.1-mc1.16.3.jar Obfuscate {obfuscate@0.5.1 NONE}
		physics-mod-1.3.4_forge.jar Physics Mod {physicsmod@1.0 NONE}
		vehicle-0.45.1-mc1.16.3.jar MrCrayfish's Vehicle Mod {vehicle@0.45.1 NONE}
		worldedit-forge-mc1.16.3-7.2.1-dist.jar WorldEdit {worldedit@7.2.1+299386a NONE}
		forge-1.16.3-34.1.1-universal.jar Forge {forge@34.1.1 NONE}
		forge-1.16.3-34.1.1-client.jar Minecraft {minecraft@1.16.3 NONE}
	Launched Version: 1.16.3-forge-34.1.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.77, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G5
	OptiFine Build: 20201106-202857
	Render Distance Chunks: 19
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 466.77
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by CeruleanDerpo** [comment]
I have no idea on why it happens but I hope it gets fixed soon :)

**Comment by haubna** [comment]
Forge 1.16.3 was never supported.
