### ISSUE TITLE
[BUG] Forge version with Optifine, crashes.

### ISSUE THREAD

**Issue by BTFighter** [haubna/PhysicsMod#133]
Version: 1.17.1
Forge version: 37.0.70
Item Physics version: 2.5.11
Optifine Version: HD U G9

Error Log:
[10:46:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.1 by Microsoft
Exception in thread "main" java.lang.IllegalArgumentException: OptiFine.1.17.1.HD.U.G9.MOD: Invalid module name: '1' is not a Java identifier
	at java.base/jdk.internal.module.Checks.requireModuleName(Checks.java:52)
	at java.base/java.lang.module.ModuleDescriptor$Builder.<init>(ModuleDescriptor.java:1523)
	at java.base/java.lang.module.ModuleDescriptor.newAutomaticModule(ModuleDescriptor.java:2405)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.impl.SimpleJarMetadata.descriptor(SimpleJarMetadata.java:13)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.JarModuleFinder.lambda$new$0(JarModuleFinder.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:82)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:129)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

More Information:
Only both Optifine and Physics mod are installed.
It crashes instantly when I start Minecraft.

**Comment by haubna** [comment]
Have you tried only Optifine? It doesn't work with the new Forge versions.
Not a Physics Mod crash :P

BTFighter ***@***.***> schrieb am Mo. 20. Sep. 2021 um 04:52:

**Comment by BTFighter** [comment]
That makes sense, I'll check.

**Comment by BTFighter** [comment]
Yep, it crashes only with Optifine, thanks for the response!
