### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Goldy769** [haubna/PhysicsMod#14]
When you die the game crashes thats it

**Comment by haubna** [comment]
Try the newest version and let me know if it is fixed

**Comment by Goldy769** [comment]
> Try the newest version and let me know if it is fixed

I will but not now

**Comment by Goldy769** [comment]
> Try the newest version and let me know if it is fixed

i was using the latest version so the problem isnt about that

**Comment by haubna** [comment]
Forge or Fabric?

**Comment by Goldy769** [comment]
> Forge or Fabric?

Forge 1.16.4

**Comment by Goldy769** [comment]
Well Did you saw my comment?

**Comment by haubna** [comment]
Yes, currently not at home, sorry :o

**Comment by Goldy769** [comment]
oh no problem man but i wish i can use it on my survival worlds too but its not possible on this condition because you know if i try survival its instantly hardcore mode on xD

**Comment by haubna** [comment]
I think you are not using the latest version. It's not happening on my end. Make sure you are using no incompatible mod like replay mod.

**Comment by Goldy769** [comment]
i was on verdion 1.1.1 isnt it the latest one? and i tried it with no mods too

**Comment by haubna** [comment]
I just tried it the exact same way. Nothing crashed. Maybe you are not on the latest Forge version?

**Comment by Goldy769** [comment]
> I just tried it the exact same way. Nothing crashed. Maybe you are not on the latest Forge version?

yes i am on the 36 one not the 37

**Comment by Goldy769** [comment]
i will try the latest forge version later

**Comment by haubna** [comment]
I can't reproduce the error. Do you have a crash log for me?

**Comment by Goldy769** [comment]
> I can't reproduce the error. Do you have a crash log for me?

well i am not on my PC right now but when i have my PC i can send one if the latest forge version doesnt work

**Comment by Goldy769** [comment]
i tried the forge version 35.1.37 and it crashed again when i died so here is the crash log:





---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 07.02.2021 14:22
Description: Unexpected error

java.lang.ClassCastException: com.google.common.collect.FluentIterable$2 cannot be cast to java.util.List
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:313) ~[?:1.0] {re:classloading,re:mixin}
	at net.diebuddies.physics.PhysicsMod.onPlayerDeath(PhysicsMod.java:223) ~[?:1.0] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.ASMEventHandler_16_PhysicsMod_onPlayerDeath_RenderTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2571/260461891.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickStart(BasicEventHooks.java:75) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.37.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/2115087165.call(Unknown Source) [forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:313) ~[?:1.0] {re:classloading,re:mixin}
	at net.diebuddies.physics.PhysicsMod.onPlayerDeath(PhysicsMod.java:223) ~[?:1.0] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.ASMEventHandler_16_PhysicsMod_onPlayerDeath_RenderTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2571/260461891.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['MrGoldy769'/134, l='ClientLevel', x=-50.66, y=70.00, z=120.64]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,68,128), Chunk: (at 0,4,0 in -3,8; contains blocks -48,0,128 to -33,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3910 game time, 3910 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.37.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/2115087165.call(Unknown Source) [forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 14319674632 bytes (13656 MB) / 15032385536 bytes (14336 MB) up to 15032385536 bytes (14336 MB)
	CPUs: 16
	JVM Flags: 10 total; -Xmn128M -Xmx14310M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		physics-mod-1.0.9_forge.jar                       |Physics Mod                   |physicsmod                    |1.0                 |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: ad3668ea-8f84-4db6-8686-bc5a6f04f163
	Launched Version: 1.16.4-forge-35.1.37
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

**Comment by haubna** [comment]
You aren't using the latest version of the mod...

**Comment by Goldy769** [comment]
also i wanted to say one more thing i closed the mob pieces mechanic and it didnt crashed so i guess the problem is about that pieces when a mob dies

**Comment by haubna** [comment]
See the answer above.

**Comment by Goldy769** [comment]
yes i saw it i just wanted to add this info

**Comment by Goldy769** [comment]
i am downloading the 1.1.1 version right now

**Comment by haubna** [comment]
Yeah but this is already fixed like I said before. Next time don't ensure you are using the latest version if you aren't using it.

**Comment by Goldy769** [comment]
thanks for helping it solved the problem :) i am sure this mod will be a masterpiece!
