### ISSUE TITLE
Bug description [Vindicator crashing client]

### ISSUE THREAD

**Issue by Kazzc** [haubna/PhysicsMod#185]
**Describe the bug**
When I have mob physics enabled and I encounter an area where Vindicators spawn it crashes the client. It's inconsistent.

**To Reproduce**
Explore and find a Vindicator while having resourcepack ``Fresh Animations`` and ``Reimagined``

**Screenshots**
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.physics.PhysicsMod.addCuboid(PhysicsMod.java:410) ~[physicsmod:1.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.model.ModelRenderer.handler$bed000$doRender(ModelRenderer.java:527) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.model.ModelRenderer.func_228306_a_(ModelRenderer.java) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.model.ModelRenderer.func_228309_a_(ModelRenderer.java:208) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.model.ModelRenderer.func_228309_a_(ModelRenderer.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.model.ModelRenderer.func_228309_a_(ModelRenderer.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.model.ModelRenderer.func_228309_a_(ModelRenderer.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinModelPart,pl:mixin:A}
	at net.minecraft.client.renderer.entity.model.SegmentedModel.func_228272_a_(SourceFile:23) ~[?:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?] {re:computing_frames}
	at net.minecraft.client.renderer.entity.model.SegmentedModel.func_225598_a_(SourceFile:23) ~[?:?] {re:classloading}
	at com.mrcrayfish.obfuscate.client.Hooks.fireRenderPlayer(Hooks.java:49) ~[obfuscate:0.6.2-1.16.3] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.redirect$zfn000$fireRenderPlayer(LivingRenderer.java:541) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:197) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
-- Entity being rendered --
Details:
	Entity Type: minecraft:vindicator (net.minecraft.entity.monster.VindicatorEntity)
	Entity ID: 160760
	Entity Name: Vindicator
	Entity's Exact location: 68.70, 64.00, -6367.54
	Entity's Block location: World: (68,64,-6368), Chunk: (at 4,4,0 in 4,-398; contains blocks 64,0,-6368 to 79,255,-6353), Region: (0,-13; contains chunks 0,-416 to 31,-385, blocks 0,0,-6656 to 511,255,-6145)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.entity.Entity.toString()" because the return value of "net.minecraft.entity.Entity.func_184187_bx()" is null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.VindicatorRenderer@446bbe17
	Location: -50.94,-7.27,-24.59 - World: (-51,-8,-25), Chunk: (at 13,-1,7 in -4,-2; contains blocks -64,0,-32 to -49,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -40.78125
	Delta: 0.1402595
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:renderer,pl:mixin:APP:seeker_compass.mixins.json:client.EntityRendererManagerMixin,pl:mixin:APP:physicsmod.mixins.json:MixinEntityRenderDispatcher,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1742) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:seeker_compass.mixins.json:client.GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}

Minecraft Version: 1.16.5
Physics Mod Version: 1.3.4 (forge)

**Comment by haubna** [comment]
Which physics mod version?

Kassc ***@***.***> schrieb am Do. 4. Nov. 2021 um 23:42:

**Comment by haubna** [comment]
You are using an outdated version of the physics mod that on Minecraft 1.16.5. This version will not get any new updates.
