### ISSUE TITLE
Crash when leaving server 1.18

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#201]
**Describe the bug**
Game sometimes crashes when leaving server

**To Reproduce**
Might be hard to reproduce only happens sometimes when clicking quit button in server to disconnect

[18:10:12] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.diebuddies.physics.ContactSimulationCallback.destroy()" because "this.contactCallback" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
	at net.diebuddies.physics.DynamicsWorld.destroy(DynamicsWorld.java:171) ~[physics-mod-2.5.17-mc-1.18-fabric.jar:?]
	at net.diebuddies.physics.PhysicsWorld.destroy(PhysicsWorld.java:516) ~[physics-mod-2.5.17-mc-1.18-fabric.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$bnn000$render(GameRenderer:4577) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [intermediary-minecraft.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]

Minecraft Version: 1.18
Physics Mod Version: physics-mod-2.5.17-mc-1.18-fabric

**Comment by haubna** [comment]
Fixed in version 2.5.18. Thanks for the report!
