### ISSUE TITLE
1.18 crash when changing dimension (going to nether from overworld/overworld to nether)

### ISSUE THREAD

**Issue by wojciechsacewicz** [haubna/PhysicsMod#202]
**crashes game on dimension change**

[13:30:36] [Render thread/INFO]: Destroying pipeline NETHER
[13:30:36] [Render thread/INFO]: Creating pipeline OVERWORLD
[13:30:36] [Render thread/WARN]: [composite1] Unsupported uniform: float BiomeTemp
[13:30:36] [Render thread/WARN]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[13:30:41] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.diebuddies.physics.ContactSimulationCallback.destroy()" because "this.contactCallback" is null
	at net.diebuddies.physics.DynamicsWorld.destroy(DynamicsWorld.java:171) ~[physics-mod-2.5.17-mc-1.18-fabric.jar:?]
	at net.diebuddies.physics.PhysicsWorld.destroy(PhysicsWorld.java:516) ~[physics-mod-2.5.17-mc-1.18-fabric.jar:?]
	at net.minecraft.class_757.handler$boh000$render(class_757.java:7077) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]

**Comment by haubna** [comment]
Fixed in version 2.5.18!
