### ISSUE TITLE
Game Crashing at random [BUG]

### ISSUE THREAD

**Issue by Zkohh** [haubna/PhysicsMod#264]
It began as a crash that would initiate as soon as I entered a world, and the crash was reported as "Exit code 0", but that problem went away (not sure how or why) and now the game crashes seemingly at random, without any sort of pattern or cause. The only consistent thing is that the game crashes soon after logging in. I usually can't play for longer than a minute or so. 

Minecraft Version: <1.18.1>
Physics Mod Version: <2.6.5>

Crash Report:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-01-22, 3:18 p.m.
Description: Exception ticking world

java.lang.NoSuchFieldError: DIRT
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2356!/:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2356!/:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['craft4thewin'/119, l='ServerLevel[New World]', x=149.50, y=9.77, z=-472.50]]
	Chunk stats: 15887
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,70,-464), Section: (at 0,6,0 in 9,4,-29; chunk contains blocks 144,-64,-464 to 159,319,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1216 game time, 1216 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 37098 (now: false), thunder time: 23358 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2396!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Mac OS X (x86_64) version 12.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1403027976 bytes (1338 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel Iris Plus Graphics 650
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x5927
	Graphics card #0 versionInfo: Revision ID: 0x0006, Adapter Firmware Version: 7.55
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 12288.00
	Virtual memory used (MB): 8798.42
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3296.00
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['craft4thewin'/119, l='ServerLevel[New World]', x=149.50, y=9.77, z=-472.50]]
	Data Packs: vanilla, mod:mcwbridges, mod:farmersdelight, mod:physicsmod (incompatible), mod:musictriggers (incompatible), mod:ambientsounds (incompatible), mod:creativecore, mod:easymagic, mod:jei (incompatible), mod:goblintraders (incompatible), mod:notenoughanimations (incompatible), mod:flywheel, mod:curios, mod:sound_physics_remastered, mod:create, mod:xaerominimap, mod:waystones, mod:villagernames, mod:timber (incompatible), mod:gravestone (incompatible), mod:collective, mod:umu_backpack (incompatible), mod:xaeroworldmap, mod:awesomedungeon, mod:comforts, mod:citadel, mod:alexsmobs (incompatible), mod:sereneseasons (incompatible), mod:configured (incompatible), mod:toughasnails (incompatible), mod:betterthirdperson, mod:effective_fg, mod:sophisticatedbackpacks (incompatible), mod:crockpot, mod:cfm (incompatible), mod:alexsdelight (incompatible), mod:balm (incompatible), mod:puzzleslib, mod:paraglider (incompatible), mod:skinlayers3d (incompatible), mod:forge, mod:seedfix_forge, mod:drinkbeer (incompatible), Music Triggers Songs
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.1 INTEL-18.3.5
	OpenGlRenderer: Intel(R) Iris(TM) Plus Graphics 650
	OpenGlVendor: Intel Inc.
	CpuCount: 4
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		physics-mod-2.6.5-mc-1.18-forge.jar               |Physics Mod                   |physicsmod                    |2.6.5               |DONE      |Manifest: NOSIGNATURE
		musictriggers-1.18.1-4.0.jar                      |Music Triggers                |musictriggers                 |1.18.1-4.0          |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.3_mc1.18.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v3.2.0-1.18.1-Forge.jar                 |Easy Magic                    |easymagic                     |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.1.0.47.jar                           |Just Enough Items             |jei                           |9.1.0.47            |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.0-1.18.1.jar                    |Goblin Traders                |goblintraders                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.4.0-mc1.18.jar        |NotEnoughAnimations Mod       |notenoughanimations           |1.4.0               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.4.2-rc.jar                  |Flywheel                      |flywheel                      |1.18-0.4.2-rc       |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.3.1.jar                   |Curios API                    |curios                        |1.18.1-5.0.3.1      |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.1-1.0.4.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4a.jar                         |Create                        |create                        |0.4a                |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.22.3.1_Forge_1.18.jar           |Xaero's Minimap               |xaerominimap                  |21.22.3.1           |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.1.jar                  |Waystones                     |waystones                     |9.0.1               |DONE      |Manifest: NOSIGNATURE
		villagernames_1.18.1-3.5.jar                      |Villager Names                |villagernames                 |3.5                 |DONE      |Manifest: NOSIGNATURE
		timber-1.18.1-3.0.0.jar                           |Timber Mod                    |timber                        |3.0.0               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		umu_backpack-1.1_1.18.1.jar                       |UMU Backpack                  |umu_backpack                  |1.1_1.18.1          |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.18.6.1_Forge_1.18.jar            |Xaero's World Map             |xaeroworldmap                 |1.18.6.1            |DONE      |Manifest: NOSIGNATURE
		awesomedungeon-1.1.3.jar                          |Awesome Dungeon               |awesomedungeon                |1.1.3               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.15.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.15.1              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.8-universal.jar        |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.8      |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.18.1-6.0.0.49-universal.jar        |Tough As Nails                |toughasnails                  |1.18.1-6.0.0.49     |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18-1.6.0.jar            |Better Third Person           |betterthirdperson             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		effective_test.jar                                |Effective (Forge)             |effective_fg                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.13.6.452.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.13.6.452   |DONE      |Manifest: NOSIGNATURE
		CrockPot-1.18.1-1.1.1-release.jar                 |Crock Pot                     |crockpot                      |1.1.1-release       |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		Alex's+Delights+1.2.0.jar                         |Alex's Delight                |alexsdelight                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		balm-2.3.1+0.jar                                  |Balm                          |balm                          |2.3.1+0             |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.1.1-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.1.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Paraglider-1.18-1.5.0.0.jar                       |Paraglider                    |paraglider                    |1.5.0.0             |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-mc1.18-1.3.1.jar               |3dSkinLayers                  |skinlayers3d                  |1.3.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.45-universal.jar                |Forge                         |forge                         |39.0.45             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Terralith_v2.0.12_Fabric+Forge.jar                |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		drinkbeer-v2.3.5+for+1.18.1.jar                   |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b31a38ee-99d1-428a-8068-be29d577bb10
	FML: 39.0
	Forge: net.minecraftforge:39.0.45

**Comment by haubna** [comment]
The crash is not caused by my mod! It is caused by this: at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn
So a mod called Alexs Mobs or something like that.
