### ISSUE TITLE
Structurize Incompatability Crash

### ISSUE THREAD

**Issue by Apothicon02** [haubna/PhysicsMod#271]
**Describe the bug**
Version 2.66 on Forge is incompatible with the Structurize mod (Dependency for mine colonies)

**To Reproduce**
Install version 2.66 of PhysicsMod with Structurize and the game will crash when loading.

Minecraft Version: <1.18.1>
Physics Mod Version: <2.66>

Logs:
[2022-01-26-1.log.gz](https://github.com/haubna/PhysicsMod/files/7944394/2022-01-26-1.log.gz)
[debug-1.log.gz](https://github.com/haubna/PhysicsMod/files/7944395/debug-1.log.gz)

**Comment by haubna** [comment]
So what I've read so far from the crash log is that Structurize crashes on its own. Not caused by my mod. Submit that bug on their issue github.

```
[26Jan2022 13:44:15.058] [Worker-Main-15/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid structurize
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
	at com.ldtteam.structurize.util.StructureLoadingUtils.addOriginFolder(StructureLoadingUtils.java:66) ~[structurize-1.18.1-1.0.326-ALPHA.jar%23104!:1.18.1-1.0.326-ALPHA]
	at com.ldtteam.structurize.util.StructureLoadingUtils.addOriginMod(StructureLoadingUtils.java:90) ~[structurize-1.18.1-1.0.326-ALPHA.jar%23104!:1.18.1-1.0.326-ALPHA]
	at com.ldtteam.structurize.util.StructureLoadingUtils.addOriginMod(StructureLoadingUtils.java:77) ~[structurize-1.18.1-1.0.326-ALPHA.jar%23104!:1.18.1-1.0.326-ALPHA]
	at com.ldtteam.structurize.event.LifecycleSubscriber.onModInit(LifecycleSubscriber.java:25) ~[structurize-1.18.1-1.0.326-ALPHA.jar%23104!:1.18.1-1.0.326-ALPHA]
	at net.minecraftforge.eventbus.ASMEventHandler_173_LifecycleSubscriber_onModInit_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.43.jar%23119!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.43.jar%23118!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```
