### ISSUE TITLE
return value of `net.diebuddies.physics.PhysicsMod.getInstance()` is null

### ISSUE THREAD

**Issue by BrekiTomasson** [haubna/PhysicsMod#28]
Getting a weird error on launch, have tested both v2.3.2 and v2.2.7; same error on both. I'm running Minecraft v1.17.1 on macOS, if that helps. Unfortunately, your code isn't open source, so I can't help you any further than that. Here's the full error log in the crash:

```
java.lang.NullPointerException: Cannot read field "time" because the return value of "net.diebuddies.physics.PhysicsMod.getInstance()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.10) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$zbo000$onRenderTick(MinecraftClient:3059) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

**Comment by haubna** [comment]
MacOS is not supported, sorry.

Breki Tomasson ***@***.***> schrieb am Di. 20. Juli 2021 um
15:55:

**Comment by BrekiTomasson** [comment]
That's a shame. Any reason why? Minecraft mods are usually quite universal when they're not directly interacting with machine hardware like microphones etc.

**Comment by haubna** [comment]
The Nvidia PhysX JNI wrapper is not built for macOS yet.

Breki Tomasson ***@***.***> schrieb am Di. 20. Juli 2021 um
16:09:

**Comment by haubna** [comment]
I have some good news for you. If you want mac support you simply need to compile the natives and submit it. Here is the issue for that: https://github.com/fabmax/physx-jni/issues/21

**Comment by BrekiTomasson** [comment]
Ah, got it! Thanks, I'll give that a shot!

**Comment by haubna** [comment]
MacOS is now supported with version 2.4.10.
