### ISSUE TITLE
Crashes with Mac M1 native version

### ISSUE THREAD

**Issue by SkyCube08** [haubna/PhysicsMod#291]
**Describe the bug**
Minecraft crashes on my m1 mac when using the native method with MultiMC. It works using Rosetta 2.

**To Reproduce**
-Download MultiMC and install the native method (m1-multimc-hack) for Minecraft on M1
-Launch Minecraft with fabric, fabric-api and physics mod
-Game crashes

**Screenshots**
--

Minecraft Version: 1.18.1
Physics Mod Version: 2.6.7 lite
[crash-client.txt](https://github.com/haubna/PhysicsMod/files/8153654/crash-client.txt)

**Comment by haubna** [comment]
M1 might work with the upcoming update but I can't guarantee it. Depends on the compiled natives from the PhysX Java Wrapper.

**Comment by leobeekay** [comment]
Same issue, another log just in case:

[physicsmod crash M1.log](https://github.com/haubna/PhysicsMod/files/8672715/physicsmod.crash.M1.log)

**Comment by recsdj** [comment]
@haubna , sorry I'm total noob to Java, and most likely you're already aware about these issues on M1, but this may help to fix M1 issues:
https://stackoverflow.com/questions/70368863/unsatisfiedlinkerror-for-m1-macs-while-running-play-server-locally

**Comment by movy** [comment]
I managed to make PhysicsMod run on M1 using dylib from #151 , just repacked the original .jar with the arm64 lib, replacing x64-one inside `macos/` folder. 

`jar -uf physics-mod-2.7.2-mc-22w17a-fabric.jar -C . macos/libPhysXJniBindings_64.dylib`

**Comment by ipiiia** [comment]
> I managed to make PhysicsMod run on M1 using dylib from #151 , just repacked the original .jar with the arm64 lib, replacing x64-one inside `macos/` folder.
> 
> `jar -uf physics-mod-2.7.2-mc-22w17a-fabric.jar -C . macos/libPhysXJniBindings_64.dylib`

can you explain it in more detail?🥲 delete original dylib > rename arm to 64 > replace..this is right?

**Comment by movy** [comment]
No need to delete anything, just download new dylib from #151 , rename it to `libPhysXJniBindings_64.dylib` and put into empty `macos` folder. Download the latest version of physics-mod .jar and replace the dylib inside the jar with the renamed one:

`jar -uf physics-mod-2.7.2-mc-22w17a-fabric.jar -C . macos/libPhysXJniBindings_64.dylib`

**Comment by ipiiia** [comment]
> No need to delete anything, just download new dylib from #151 , rename it to `libPhysXJniBindings_64.dylib` and put into empty `macos` folder. Download the latest version of physics-mod .jar and replace the dylib inside the jar with the renamed one:
> 
> `jar -uf physics-mod-2.7.2-mc-22w17a-fabric.jar -C . macos/libPhysXJniBindings_64.dylib`

Thank you! but I followed your explanation exactly, and the crash still occurred😭(tested on fabric, forge, 1.18, 1.19, physics2.6.6~2.7.5)

**Comment by movy** [comment]
can you paste a log related to the crash? What launcher are you using?

**Comment by ipiiia** [comment]
> can you paste a log related to the crash? What launcher are you using?
```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/25/22, 11:48 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:150)
	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 15 more
Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
	at de.fabmax.physxjni.Loader.load(Loader.java:38)
	at physx.NativeObject.<clinit>(NativeObject.java:7)
	... 18 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/w5/nl1zrb5d2tb_4_y6z8wzsnp40000gn/T/de.fabmax.physx-jni/1.0.0/libPhysXJniBindings_64.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
	at de.fabmax.physxjni.Loader.load(Loader.java:33)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (aarch64) version 12.5
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 4098744760 bytes (3908 MiB) / 4731174912 bytes (4512 MiB) up to 12582912000 bytes (12000 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Max
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M1 Max
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 65536.00
	Virtual memory used (MB): 18346.13
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx12000m
	Fabric Mods: 
		fabric: Fabric API 0.53.3+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.4+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.18+01a4d43d60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.15+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.1+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.6
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		physicsmod: Physics Mod 2.7.5
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

I used ManyMC version: 0.0.9!

**Comment by movy** [comment]
ManyMC is a good choice, the error looks exactly the same as if you're still using old version of the library. I've attached my build, try using this one and see if error still there. Not hte latest physics mod, but it works for me at least. 

[physics-mod-2.7.2-mc-M1-22w17a-fabric.jar.zip](https://github.com/haubna/PhysicsMod/files/8776405/physics-mod-2.7.2-mc-M1-22w17a-fabric.jar.zip)
.

**Comment by ipiiia** [comment]
> ManyMC is a good choice, the error looks exactly the same as if you're still using old version of the library. I've attached my build, try using this one and see if error still there. Not hte latest physics mod, but it works for me at least.
> 
> [physics-mod-2.7.2-mc-M1-22w17a-fabric.jar.zip](https://github.com/haubna/PhysicsMod/files/8776405/physics-mod-2.7.2-mc-M1-22w17a-fabric.jar.zip) .

I tested it with the jar you uploaded, but the same error occurs as before.
Maybe I should wait for the update.. Anyway, thank you so much for your help!

**Comment by movy** [comment]
Sorry I could not help, hope you can figure this out! M1 rocks! :)

**Comment by haubna** [comment]
Physics Mod 3.0.0 added Mac support.
