### ISSUE TITLE
Game Crash Error 225 on M1 Macbook Air

### ISSUE THREAD

**Issue by StillCreative** [haubna/PhysicsMod#372]
I saw this bug is already reported, but that bug reported 2.6.7, whereas I played with 2.6.10 and it worked fine but when I updated to 2.8.0 it came back. 
This isn't as much a bug report as it is a request to add a 1.19.x version of 2.6.10 or a later ARM-compatible version until the bug is fixed. Not to rush of course.

To reproduce:
Attempt to launch the mod on 2.8.0 on an M1 chipped Mac. 

If it helps any,

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/7/22, 5:55 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:153)
	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
	at de.fabmax.physxjni.Loader.load(Loader.java:38)
	at physx.NativeObject.<clinit>(NativeObject.java:7)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/zf/z0c3nq2x6ss8t5n40ng71cb80000gp/T/de.fabmax.physx-jni/1.0.0/libPhysXJniBindings_64.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
	at de.fabmax.physxjni.Loader.load(Loader.java:33)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.3.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1068959024 bytes (1019 MiB) / 1543503872 bytes (1472 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6857.45
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 272.25
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: Cloth Config v6 7.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric: Fabric API 0.55.2+1.19
			fabric-api-base: Fabric API Base 0.4.8+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.5+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.11+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.17+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.4+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.0+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.21+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.26+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.15+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.7+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.2+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.0+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.26+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.15+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.25+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.23+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.18+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.3+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.22+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.17+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.15+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.8+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.0+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.14+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.26+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.13+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.4+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.7+9ff28f40a9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.15+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.7+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.5+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.17+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.11+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.4+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.19+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.13+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.8+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.22+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.5+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.17+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.7+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+9e7660c6a9
		fabricloader: Fabric Loader 0.14.6
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19
		physicsmod: Physics Mod 2.8.0
	Launched Version: fabric-loader-0.14.6-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

Minecraft Version: 1.19
Physics Mod Version: 2.8.0

**Comment by haubna** [comment]
You probably played the old version in M1 compatibility mode or something like that. It shouldn't have worked back then.

**Comment by haubna** [comment]
Physics Mod 3.0.0 added Mac support.
