### ISSUE TITLE
i get this error on 1.16.5 forge 36.1.31 when a cyclops from ice and fire bites a sheep with ragdoll physics on

### ISSUE THREAD

**Issue by Mr-Syntax** [haubna/PhysicsMod#48]
[02:19:13] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalStateException: handling packet in ResourceKey[minecraft:dimension / minecraft:overworld]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$doProcessRedirectedMessage$3(CommonNetworkClient.java:81) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$35013/1794293812.get(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.lambda$throwException$2(LimitedLogger.java:33) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.my_util.LimitedLogger$$Lambda$35014/494314484.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.invoke(LimitedLogger.java:27) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.my_util.LimitedLogger.throwException(LimitedLogger.java:32) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.doProcessRedirectedMessage(CommonNetworkClient.java:80) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$processRedirectedPacket$0(CommonNetworkClient.java:46) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$34139/607814035.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.CHelper.executeOnRenderThread(CHelper.java:152) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.processRedirectedPacket(CommonNetworkClient.java:53) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.doProcessRedirectedPacket(StcRedirected.java:55) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.lambda$handle$0(StcRedirected.java:77) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected$$Lambda$34138/639161992.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.handle(StcRedirected.java:77) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$25633/1836982765.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$33321/449532962.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3028/1286885448.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3030/1564559683.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2620/919686568.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$33309/1114580294.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$33667/1349890900.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.31.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1019474238.call(Unknown Source) [forge-1.16.5-36.1.31.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.NullPointerException
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:371) ~[?:1.0]
	at net.diebuddies.physics.PhysicsMod.onEntityDeath(PhysicsMod.java:219) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_992_PhysicsMod_onEntityDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2620/919686568.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:373) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1183) ~[?:?]
	at net.mcreator.zmonsters.entity.StrigaEntity$CustomEntity.func_70645_a(StrigaEntity.java:231) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70103_a(LivingEntity.java:1607) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70103_a(MobEntity.java:412) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147236_a(ClientPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.server.SEntityStatusPacket.func_148833_a(SourceFile:37) ~[?:?]
	at net.minecraft.network.play.server.SEntityStatusPacket.func_148833_a(SourceFile:11) ~[?:?]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.lambda$doProcessRedirectedMessage$2(CommonNetworkClient.java:77) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient$$Lambda$34141/2028360646.run(Unknown Source) ~[?:?]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.withSwitchedWorld(CommonNetworkClient.java:107) ~[?:0.16-mc1.16.5-forge]
	at com.qouteall.immersive_portals.network.CommonNetworkClient.doProcessRedirectedMessage(CommonNetworkClient.java:77) ~[?:0.16-mc1.16.5-forge]
	... 51 more

**Comment by haubna** [comment]
Legacy versions of Minecraft will not get any bugfixes, sorry!
