### ISSUE TITLE
incompatible with Valkyrien Skies mod,crash on startup [BUG]

### ISSUE THREAD

**Issue by supershorty1** [haubna/PhysicsMod#480]
**Describe the bug**
crash on startup

**To Reproduce**
install both Valkyrien Skies mod and Physics mod

**Screenshots**

Minecraft Version: 1.18.2
Physics Mod Version: Physics 2.9.4 

Exception in thread "main" java.lang.module.ResolutionException: Modules physicsmod and org.joml export package org.joml to module bowinfinityfix
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by haubna** [comment]
Seems like bowinfinityfix is causing this crash

EDIT: scratch that. I have no clue why it crashes.

**Comment by DJHugal** [comment]
I really like both mods, hope this gets fixed :/

**Comment by bloxspace12345** [comment]
I can confirm that this mod is incompatible with Valkyrien Skies as I have just tested it out (I am using the 1.18.2 version as well as the pro version of of Physics mod); to replicate just install Valkyrien Skies mod along with its required dependencies and then install it with physics mod then run. The game crashes before startup throwing an "exit code 1";

**Comment by supershorty1** [comment]
seems fixed in latest version
