### ISSUE TITLE
The Physics Mod Crashes often 1.17.1

### ISSUE THREAD

**Issue by juliusgunnars** [haubna/PhysicsMod#54]
Hello, I'm not very sure how this is happening, I only have ragdoll enabled this only happens in LAN, or if you're unlucky servers even, this has probably something with players changing gamemodes.

When it crashes, a loading screen will pop up and the text says  "Saving World..." even if you're on a server with thousands on, and then it will crash.

Game Version: 1.17.1

Mod Version: 2.3.5

This is the crash message:

java.lang.NullPointerException: Cannot invoke "physx.NativeObject.getAddress()" because "value" is null
	at physx.common.PxBoundedData.setData(PxBoundedData.java:121)
	at net.diebuddies.physics.ConvexRigidBodyPX.create(ConvexRigidBodyPX.java:98)
	at net.diebuddies.physics.PhysicsWorldPX.addBlockParticle(PhysicsWorldPX.java:701)
	at net.diebuddies.physics.PhysicsWorldPX.addRagdoll(PhysicsWorldPX.java:600)
	at net.minecraft.class_761.updatePhysics(class_761.java:3573)
	at net.minecraft.class_761.handler$zzm000$renderLayer(class_761.java:3384)
	at net.minecraft.class_761.method_3251(class_761.java:1608)
	at net.minecraft.class_761.method_22710(class_761.java:1166)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by haubna** [comment]
This error should only happen when a certain mob dies. If you figure out which mob I can adjust the ragdoll for it (also future releases will no longer crash in such cases).

**Comment by haubna** [comment]
Fixed in version 2.3.6
