### ISSUE TITLE
Crash the mod with MultiMC in a MacStudio at launch moment.

### ISSUE THREAD

**Issue by wilebaldo** [haubna/PhysicsMod#558]
**Describe the bug**
Minecraft crash while opening

`// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-01-29 15:17:27
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:196)
	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more
Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
	at de.fabmax.physxjni.Loader.load(Loader.java:38)
	at physx.NativeObject.<clinit>(NativeObject.java:7)
	... 17 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/g0/2ld7hv_d6ss166q5rw3jhjd40000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
	at de.fabmax.physxjni.Loader.load(Loader.java:33)
	... 18 more`

**To Reproduce**
Just start the physic mods most new version for 1.19.2 in the moment of the loading is crash because this mod.

**Screenshots**
![Screenshot 2023-01-29 at 3 18 58 PM](https://user-images.githubusercontent.com/8034131/215361456-959c6bb9-2a74-4f27-99e1-d04c6bf5a49d.jpg)

Minecraft Version: Minecraft 1.19.2, with MultiMC Launcher on a mac studio.

Physics Mod Version: 2.10.1 or 2.10.0 is the same problem

**Comment by haubna** [comment]
Mac is not supported

**Comment by wilebaldo** [comment]
The mod before was support, I tested by my self in a mac mini m1 with minecraft 1.18.1

https://youtube.com/shorts/GXwWTm3Fzxg?feature=share

**Comment by wilebaldo** [comment]
I just check the version release for this mod and since the version 2.8.11 MacOS native supported.

![Screenshot 2023-01-30 at 6 47 20 PM](https://user-images.githubusercontent.com/8034131/215650045-ea058419-a881-40e8-a244-fe1a9a56bd96.jpg)
