### ISSUE TITLE
Cannot invoke "physx.NativeObject.getAddress()" because "value" is null

### ISSUE THREAD

**Issue by EpicnessTwo** [haubna/PhysicsMod#62]
I'm getting this error randomly whilst playing with this mod. I've tried using just the mod on it's own and still get it.

Using Fabric 0.11.6

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 01/08/2021, 15:52
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "physx.NativeObject.getAddress()" because "value" is null
	at physx.common.PxBoundedData.setData(PxBoundedData.java:121)
	at net.diebuddies.physics.ConvexRigidBodyPX.create(ConvexRigidBodyPX.java:98)
	at net.diebuddies.physics.PhysicsWorldPX.addBlockParticle(PhysicsWorldPX.java:701)
	at net.diebuddies.physics.PhysicsWorldPX.createChildLink(PhysicsWorldPX.java:655)
	at net.diebuddies.physics.PhysicsWorldPX.addRagdoll(PhysicsWorldPX.java:607)
	at net.minecraft.class_761.updatePhysics(class_761.java:8073)
	at net.minecraft.class_761.handler$zcl000$renderLayer(class_761.java:7884)
	at net.minecraft.class_761.method_3251(class_761.java:5333)
	at net.minecraft.class_761.invokeRenderLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:345)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:469)
	at net.minecraft.class_761.handler$zkh000$iris$renderTerrainShadows(class_761.java:10118)
	at net.minecraft.class_761.method_22710(class_761.java:1160)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at physx.common.PxBoundedData.setData(PxBoundedData.java:121)
	at net.diebuddies.physics.ConvexRigidBodyPX.create(ConvexRigidBodyPX.java:98)
	at net.diebuddies.physics.PhysicsWorldPX.addBlockParticle(PhysicsWorldPX.java:701)
	at net.diebuddies.physics.PhysicsWorldPX.createChildLink(PhysicsWorldPX.java:655)
	at net.diebuddies.physics.PhysicsWorldPX.addRagdoll(PhysicsWorldPX.java:607)
	at net.minecraft.class_761.updatePhysics(class_761.java:8073)
	at net.minecraft.class_761.handler$zcl000$renderLayer(class_761.java:7884)
	at net.minecraft.class_761.method_3251(class_761.java:5333)
	at net.minecraft.class_761.invokeRenderLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:345)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:469)
	at net.minecraft.class_761.handler$zkh000$iris$renderTerrainShadows(class_761.java:10118)
	at net.minecraft.class_761.method_22710(class_761.java:1160)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['EpicKitty'/608349, l='ClientLevel', x=4397.10, y=0.00, z=4382.15]]
	Chunk stats: 1024, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (4400,0,4381), Section: (at 0,0,13 in 275,0,273; chunk contains blocks 4400,-64,4368 to 4415,319,4383), Region: (8,8; contains chunks 256,256 to 287,287, blocks 4096,-64,4096 to 4607,319,4607)
	Level time: 140336 game time, 61938540 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r865508.zip, VanillaTweaks_r934511.zip, Black Icons, Better+Font+6.zip, charmonium/journeyman

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 487516184 bytes (464 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
	Identifier: Intel64 Family 6 Model 44 Stepping 2
	Microarchitecture: Westmere (Server)
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon (TM) RX 480 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.22017.1004
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 0.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 0.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 0.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 0.40
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 0.40
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MB): 4096.00
	Memory slot #5 clockSpeed (GHz): 0.80
	Memory slot #5 type: Unknown
	Virtual memory max (MB): 44019.98
	Virtual memory used (MB): 28901.24
	Swap memory total (MB): 29685.56
	Swap memory used (MB): 2776.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		axolotlitemfix: Axolotl Item Fix 1.1.1
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.9-fabric
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterf3: BetterF3 1.1.5
		charmonium: Charmonium 3.3.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		customstars: Custom Stars 0.5
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		iris: Iris 1.1.1
		java: OpenJDK 64-Bit Server VM 16
		lambdynlights: LambDynamicLights 2.0.1+1.17
		libzoomer: LibZoomer 0.2.1+1.17
		litematica: Litematica 0.0.0-dev.20210616.033538
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		modmenu: Mod Menu 2.0.2
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omniscience: Omniscience 1.3
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		physicsmod: Physics Mod 2.3.5
		searchablecontainers: Searchable Containers 1.3
		sodium: Sodium 0.3.0+IRIS2
		spruceui: SpruceUI 3.2.0+1.17
		tweed: Tweed 3.0.0-beta.26
		voicechat: Simple Voice Chat 1.17.1-1.0.6
		watson: Watson 1.11.0.20210703.224053
		xaerominimap: Xaero's Minimap 21.13.0
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon (TM) RX 480 Graphics GL version 3.2.14741 Core Profile Forward-Compatible Context 21.7.1 27.20.22017.1004, ATI Technologies Inc.
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r865508.zip, file/VanillaTweaks_r934511.zip, Black Icons, file/Better+Font+6.zip (incompatible), charmonium/journeyman
	Current Language: English (US)
	CPU: 12x Intel(R) Xeon(R) CPU X5680 @ 3.33GHz
```

**Comment by haubna** [comment]
Make sure to use the latest version of the mod. Should be fixed there.
