### ISSUE TITLE
Crashes on Startup with Prism Launcher (macOS, M2 Chip)

### ISSUE THREAD

**Issue by RosivDamotil** [haubna/PhysicsMod#624]
**Describe the bug**
Game won't load.

**To Reproduce**
Activate Physics Mod in Launcher and start game

**Log**
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.ExceptionInInitializerError
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:221)
	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
	at de.fabmax.physxjni.Loader.load(Loader.java:38)
	at physx.NativeObject.<clinit>(NativeObject.java:7)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/h8/tjs29trx1cv36xcndg_kh5z00000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib: dlopen(/private/var/folders/h8/tjs29trx1cv36xcndg_kh5z00000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib, 0x0001): tried: '/private/var/folders/h8/tjs29trx1cv36xcndg_kh5z00000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/h8/tjs29trx1cv36xcndg_kh5z00000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (no such file), '/private/var/folders/h8/tjs29trx1cv36xcndg_kh5z00000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71)
	at de.fabmax.physxjni.Loader.load(Loader.java:33)
	... 14 more

Minecraft Version: 1.19.4
Physics Mod Version: 2.12.0

**Comment by haubna** [comment]
Macs are only supported with Physics Mod 3.0.0 and onwards

**Comment by Macintosh-Fan** [comment]
Will there be possible support for 1.19 (specifically 1.19.2 for me) for Apple Silicon?
