### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4 + Crash Log

### ISSUE THREAD

**Issue by dareksan3KY** [haubna/PhysicsMod#63]
Using new blocky mode cause crash when destroy any block

---- Minecraft Crash Report ----
// There are four lights!

Time: 02.08.2021, 21:57
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at net.diebuddies.physics.ItemVertexConsumer.method_22920(ItemVertexConsumer.java:138)
	at net.minecraft.class_778.renderQuadSmooth(class_778.java:299)
	at net.minecraft.class_778.renderQuadsSmooth(class_778.java:269)
	at net.minecraft.class_778.renderModelSmooth(class_778.java:161)
	at net.minecraft.class_778.renderModel(class_778.java:107)
	at net.minecraft.class_776.renderModel(class_776.java:87)
	at net.minecraft.class_776.method_3355(class_776.java:78)
	at net.minecraft.class_761.updatePhysics(class_761.java:3511)
	at net.minecraft.class_761.handler$zbf000$renderLayer(class_761.java:3385)
	at net.minecraft.class_761.method_3251(class_761.java:2481)
	at net.minecraft.class_761.method_22710(class_761.java:1670)
	at net.minecraft.class_757.method_3188(class_757.java:1532)
	at net.minecraft.class_757.method_3192(class_757.java:1154)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.physics.ItemVertexConsumer.method_22920(ItemVertexConsumer.java:138)
	at net.minecraft.class_778.renderQuadSmooth(class_778.java:299)
	at net.minecraft.class_778.renderQuadsSmooth(class_778.java:269)
	at net.minecraft.class_778.renderModelSmooth(class_778.java:161)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:oak_leaves}[distance=7,persistent=false]
	Block location: World: (91,72,-74), Section: (at 11,8,6 in 5,4,-5; chunk contains blocks 80,0,-80 to 95,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Using AO: true
	Model class: net.minecraft.class_1093
	Is Fabric model: true
	Is adapted vanilla model: true
Stacktrace:
	at net.minecraft.class_778.renderModel(class_778.java:107)

-- Block being tesselated --
Details:
	Block: Block{minecraft:oak_leaves}[distance=7,persistent=false]
	Block location: World: (91,72,-74), Section: (at 11,8,6 in 5,4,-5; chunk contains blocks 80,0,-80 to 95,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block render type: MODEL
Stacktrace:
	at net.minecraft.class_776.renderModel(class_776.java:87)
	at net.minecraft.class_776.method_3355(class_776.java:78)
	at net.minecraft.class_761.updatePhysics(class_761.java:3511)
	at net.minecraft.class_761.handler$zbf000$renderLayer(class_761.java:3385)
	at net.minecraft.class_761.method_3251(class_761.java:2481)
	at net.minecraft.class_761.method_22710(class_761.java:1670)
	at net.minecraft.class_757.method_3188(class_757.java:1532)

-- Affected level --
Details:
	All players: 1 total; [class_746['dareksan3'/190, l='ClientLevel', x=91.02, y=71.00, z=-77.94]]
	Chunk stats: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,76,-48), Section: (at 0,12,0 in 5,4,-3; chunk contains blocks 80,0,-48 to 95,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2686 game time, 3687 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:476)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Patrix_1.16_32x_basic_default.zip, Leaf+Disabler.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1757608072 bytes (1676 MiB) / 2818572288 bytes (2688 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-6300 Six-Core Processor             
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 3,52
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 12285,53
	Virtual memory used (MB): 8093,40
	Swap memory total (MB): 4096,00
	Swap memory used (MB): 113,10
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		optifabric: OptiFabric 1.11.18
		physicsmod: Physics Mod 2.4.1
		xaerominimap: Xaero's Minimap 21.14.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Patrix_1.16_32x_basic_default.zip (incompatible), file/Leaf+Disabler.zip (incompatible), Fabric Mods
	Current Language: Polski (Polska)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	Player Count: 1 / 8; [class_3222['dareksan3'/190, l='ServerLevel[Nowy świat]', x=91.02, y=71.00, z=-77.94]]
	Data Packs: vanilla, Fabric Mods, file/RocketLauncher (incompatible)
	OptiFine Version: OptiFine_1.17.1_HD_U_G9_pre32
	OptiFine Build: 20210725-010158
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 471.11
	OpenGlRenderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9_pre32
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Ky/AppData/Roaming/1.17/.optifine/OptiFine_1.17.1_HD_U_G9_pre32/Optifine-mapped.jar
	OptiFabric error: -<None>-

**Comment by haubna** [comment]
My buest guess is that Optifine is causing this issue. Currently it is not supported and I suggest using Iris (way better performance anyways). However I will have a look at it. Not sure if I can fix it though.

**Comment by haubna** [comment]
Added Optifine compatibility with version 2.4.2
