### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by chair-man-f** [haubna/PhysicsMod#649]
By the way, I downloaded the ARM 64 version of azul java but it shows up as 32 bit

I have a macbook pro with m1 pro chip

**Describe the bug**
crashes and doesn't launch

**To Reproduce**
install the mod and launch like any other mod

**Screenshots**
![SCR-20230509-nil](https://github.com/haubna/PhysicsMod/assets/117324349/c70fdc2a-e4aa-4ad6-809e-51b9dbf03ca7)
![SCR-20230509-nir](https://github.com/haubna/PhysicsMod/assets/117324349/74c28f0d-65a1-4ebe-9082-12562f8f62f2)
![SCR-20230509-nm1](https://github.com/haubna/PhysicsMod/assets/117324349/c46866be-6abe-463e-a558-4a124484cc28)

Minecraft Version: 23w18a snapshot
Physics Mod Version: version for fabric 23w18a

**Minecraft log:**

MultiMC version: 0.7.0-3736

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.66.129, 65.8.66.50, 65.8.66.21, 65.8.66.25]

session.minecraft.net resolves to:
    [2620:1ec:4f:1::70, 2620:1ec:4e:1::70, 13.107.238.70, 13.107.237.70]

textures.minecraft.net resolves to:
    [2620:1ec:4f:1::70, 2620:1ec:4e:1::70, 13.107.237.70, 13.107.238.70]

api.mojang.com resolves to:
    [2620:1ec:4f:1::70, 2620:1ec:4e:1::70, 13.107.237.70, 13.107.238.70]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/23w18a/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-20.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 20.0.1, using 32-bit architecture, from Azul Systems, Inc..

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Applications/MultiMC.app/Data/instances/23w18a/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Using system OpenAL.
Using system GLFW.

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/4.0.42/authlib-4.0.42.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Applications/MultiMC.app/Data/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Applications/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/intermediary/23w18a/intermediary-23w18a.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /Applications/MultiMC.app/Data/libraries/net/fabricmc/fabric-loader/0.14.19/fabric-loader-0.14.19.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/23w18a/minecraft-23w18a-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Mods:
  [✔️] fabric-api-0.80.1+1.20.jar
  [✔️] physics-mod-pro-v153b-fabric-23w18a.jar
  [✔️] sodium-fabric-mc23w18a-0.4.11rev.f773c15.jar

Params:
  --username  --version 23w18a --gameDir /Applications/MultiMC.app/Data/instances/23w18a/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType snapshot

Window size: 960 x 540

Java Arguments:
[-Dfml.earlyprogresswindow=false, -Xdock:icon=icon.png, -Xdock:name="MultiMC: 23w18a", -XstartOnFirstThread, -Xms200m, -Xmx5000m, -Duser.language=en]

Wrapper command is:
/Users/jackie/Minecraft/m1-multimc-hack/mcwrap.py

Minecraft process ID: 97034

Using onesix launcher.

[16:53:45] [main/INFO]: Loading Minecraft 23w18a with Fabric Loader 0.14.19
[16:53:45] [main/INFO]: Loading 55 mods:
	- fabric-api 0.80.1+1.20
	   |-- fabric-api-base 0.4.26+fb8d95da6b
	   |-- fabric-api-lookup-api-v1 1.6.29+fb8d95da6b
	   |-- fabric-biome-api-v1 13.0.9+348a9c646b
	   |-- fabric-block-api-v1 1.0.8+e022e5d16b
	   |-- fabric-blockrenderlayer-v1 1.1.36+c2e6f6746b
	   |-- fabric-client-tags-api-v1 1.0.17+fb8d95da6b
	   |-- fabric-command-api-v1 1.2.29+f71b366f6b
	   |-- fabric-command-api-v2 2.2.8+fb8d95da6b
	   |-- fabric-commands-v0 0.2.46+df3654b36b
	   |-- fabric-containers-v0 0.1.58+df3654b36b
	   |-- fabric-content-registries-v0 4.0.4+b3f2574b6b
	   |-- fabric-convention-tags-v1 1.4.3+9a7c5daa6b
	   |-- fabric-crash-report-info-v1 0.2.17+aeb40ebe6b
	   |-- fabric-data-generation-api-v1 12.1.3+fb8d95da6b
	   |-- fabric-dimensions-v1 2.1.48+cbbb1b3f6b
	   |-- fabric-entity-events-v1 1.5.17+fb8d95da6b
	   |-- fabric-events-interaction-v0 0.5.0+cf56d7946b
	   |-- fabric-events-lifecycle-v0 0.2.56+df3654b36b
	   |-- fabric-game-rule-api-v1 1.0.36+b3f2574b6b
	   |-- fabric-item-api-v1 2.1.21+fb8d95da6b
	   |-- fabric-item-group-api-v1 4.0.4+b3f2574b6b
	   |-- fabric-key-binding-api-v1 1.0.35+fb8d95da6b
	   |-- fabric-keybindings-v0 0.2.33+df3654b36b
	   |-- fabric-lifecycle-events-v1 2.2.17+fb8d95da6b
	   |-- fabric-loot-api-v2 1.1.33+eff263866b
	   |-- fabric-loot-tables-v1 1.1.37+9e7660c66b
	   |-- fabric-message-api-v1 5.1.3+fb8d95da6b
	   |-- fabric-mining-level-api-v1 2.1.43+b3f2574b6b
	   |-- fabric-models-v0 0.3.32+fb8d95da6b
	   |-- fabric-networking-api-v1 1.3.5+fb8d95da6b
	   |-- fabric-networking-v0 0.3.45+df3654b36b
	   |-- fabric-object-builder-api-v1 11.0.2+fb8d95da6b
	   |-- fabric-particles-v1 1.0.25+f1e4495b6b
	   |-- fabric-recipe-api-v1 1.0.12+a1ccd7bf6b
	   |-- fabric-registry-sync-v0 2.2.2+ce75acf56b
	   |-- fabric-renderer-api-v1 2.2.8+fb8d95da6b
	   |-- fabric-renderer-indigo 1.1.4+81e8c5766b
	   |-- fabric-renderer-registries-v1 3.2.41+df3654b36b
	   |-- fabric-rendering-data-attachment-v1 0.3.30+afca2f3e6b
	   |-- fabric-rendering-fluids-v1 3.0.23+fb8d95da6b
	   |-- fabric-rendering-v0 1.1.44+df3654b36b
	   |-- fabric-rendering-v1 3.0.3+fb8d95da6b
	   |-- fabric-resource-conditions-api-v1 2.3.3+e6c7d4ee6b
	   |-- fabric-resource-loader-v0 0.11.5+bd913b0d6b
	   |-- fabric-screen-api-v1 2.0.3+8aafb8876b
	   |-- fabric-screen-handler-api-v1 1.3.24+fb8d95da6b
	   |-- fabric-sound-api-v1 1.0.11+fb8d95da6b
	   |-- fabric-transfer-api-v1 3.1.4+fb8d95da6b
	   \-- fabric-transitive-access-wideners-v1 4.0.5+cbbb1b3f6b
	- fabricloader 0.14.19
	- java 20
	- minecraft 1.20-alpha.23.18.a
	- physicsmod 3.0.4
	- sodium 0.4.11+rev.4d230b9-dirty
[16:53:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:53:45] [main/INFO]: Compatibility level set to JAVA_16
[16:53:45] [main/INFO]: Compatibility level set to JAVA_17
[16:53:45] [main/INFO]: Loaded configuration file for Sodium: 35 options available, 0 override(s) found
[16:53:45] [main/WARN]: Error loading class: software/bernie/geckolib/renderer/GeoRenderer (java.lang.ClassNotFoundException: software/bernie/geckolib/renderer/GeoRenderer)
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.preprocessor.JcppProcessor was not found physicsmod.mixins.json:iris.MixinJcppProcessor from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/ExtendedShader (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/ExtendedShader)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.pipeline.newshader.ExtendedShader was not found physicsmod.mixins.json:iris.MixinExtendedShaderAccessor from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSet (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSet)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSet was not found physicsmod.mixins.json:iris.MixinProgramSet from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/GlyphVertexExt (java.lang.ClassNotFoundException: net/coderbot/iris/compat/sodium/impl/vertex_format/entity_xhfp/GlyphVertexExt)
[16:53:45] [main/WARN]: Error loading class: net/optifine/shaders/Shaders (java.lang.ClassNotFoundException: net/optifine/shaders/Shaders)
[16:53:45] [main/WARN]: Error loading class: net/optifine/shaders/ShadersCompatibility (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersCompatibility)
[16:53:45] [main/WARN]: Error loading class: net/optifine/shaders/Programs (java.lang.ClassNotFoundException: net/optifine/shaders/Programs)
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline was not found physicsmod.mixins.json:ocean.MixinNewWorldRenderingPipeline from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSource (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSource)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSource was not found physicsmod.mixins.json:ocean.MixinProgramSource from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/preprocessor/JcppProcessor)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.preprocessor.JcppProcessor was not found physicsmod.mixins.json:ocean.MixinJcppProcessor from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/coderbot/iris/shaderpack/ProgramSet (java.lang.ClassNotFoundException: net/coderbot/iris/shaderpack/ProgramSet)
[16:53:45] [main/WARN]: @Mixin target net.coderbot.iris.shaderpack.ProgramSet was not found physicsmod.mixins.json:ocean.MixinProgramSet from mod physicsmod
[16:53:45] [main/WARN]: Error loading class: net/optifine/util/BlockUtils (java.lang.ClassNotFoundException: net/optifine/util/BlockUtils)
[16:53:45] [main/WARN]: Error loading class: ca/spottedleaf/starlight/common/light/StarLightEngine (java.lang.ClassNotFoundException: ca/spottedleaf/starlight/common/light/StarLightEngine)
[16:53:45] [main/WARN]: Error loading class: link/infra/indium/renderer/render/TerrainRenderContext (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/TerrainRenderContext)
[16:53:48] [Datafixer Bootstrap/INFO]: 187 Datafixer optimizations took 58 milliseconds
[16:53:49] [Render thread/INFO]: Launching a new process to probe the system configuration!
[16:53:49] [Render thread/INFO]: OpenGL Vendor: Apple
[16:53:49] [Render thread/INFO]: OpenGL Renderer: Apple M1 Pro
[16:53:49] [Render thread/INFO]: OpenGL Version: 4.1 Metal - 83.1
[16:53:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:53:50] [Render thread/INFO]: Setting user: Kourbi
[16:53:50] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:53:50] [Render thread/INFO]: [STDOUT]: eABORT: Allocations must be 16-byte aligned.
[16:53:50] [Render thread/INFO]: [STDERR]: java.lang.Exception: Stack trace
[16:53:50] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:2246)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.StarterClient$1.reportError(StarterClient.java:233)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at physx.common.PxErrorCallbackImpl._reportError(PxErrorCallbackImpl.java:48)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at physx.PxTopLevelFunctions._CreatePhysics(Native Method)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at physx.PxTopLevelFunctions.CreatePhysics(PxTopLevelFunctions.java:121)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:241)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:458)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:211)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:53:50] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000014305b4fc, pid=97036, tid=259
#
# JRE version: OpenJDK Runtime Environment Zulu20.30+11-CA (20.0.1+9) (build 20.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Zulu20.30+11-CA (20.0.1+9, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libPhysXJniBindings_64.dylib+0x6b4fc]  physx::PxArray<physx::Gu::MeshFactoryListener*, physx::PxReflectionAllocator<physx::Gu::MeshFactoryListener*>>::growAndPushBack(physx::Gu::MeshFactoryListener* const&)+0x14c
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/MultiMC.app/Data/instances/23w18a/.minecraft/hs_err_pid97036.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process exited with code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 09 May 2023 16:56:13 -0700

**Comment by chair-man-f** [comment]
sometimes it launches and i can edit the settings but when i join a world it crashes

**Comment by haubna** [comment]
Please just use the JVM that Vanilla Minecraft provides. As far as I know it should support M1 CPUs.

**Comment by chair-man-f** [comment]
i fixed it by using prism launcher (MultiMC doesnt support 64 bit arm)
