### ISSUE TITLE
Game crashes upon attempting to load a world.

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#657]
Whenever I try to load into a world using the physics mod (along with many others), my game crashes. Here is the crash report. Additionally, none of my resource packs seem to load either.
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-05-15 22:16:20
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.diebuddies.physics.settings.ux.ImageElement.method_25394(ImageElement.java:122)
	at net.diebuddies.physics.settings.ux.ParallaxBackground.method_25394(ParallaxBackground.java:93)
	at net.minecraft.class_437.method_25394(class_437.java:131)
	at net.diebuddies.physics.settings.PhysicsSettingsScreen.method_25394(PhysicsSettingsScreen.java:370)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_291.method_34431(class_291.java:128)
	at net.minecraft.class_291.method_34427(class_291.java:121)
	at net.minecraft.class_286.method_43438(class_286.java:33)
	at net.minecraft.class_286.method_43433(class_286.java:26)
	at net.diebuddies.physics.settings.ux.ImageElement.method_25394(ImageElement.java:122)
	at net.diebuddies.physics.settings.ux.ParallaxBackground.method_25394(ParallaxBackground.java:93)
	at net.minecraft.class_437.method_25394(class_437.java:131)
	at net.diebuddies.physics.settings.PhysicsSettingsScreen.method_25394(PhysicsSettingsScreen.java:370)
	at net.minecraft.class_437.method_47413(class_437.java:121)

-- Screen render details --
Details:
	Screen name: net.diebuddies.physics.settings.PhysicsSettingsScreen
	Mouse location: Scaled: (403, 64). Absolute: (3631.000000, 576.000000)
	Screen size: Scaled: (427, 240). Absolute: (3840, 2160). Scale factor of 9.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: vanilla, Fabric Mods
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:559)
	at net.minecraft.class_757$1.method_45777(class_757.java:437)
	at net.minecraft.class_757$1.method_18788(class_757.java:414)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/block.json: The validated expression is false
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:203)
	at net.minecraft.class_757.method_34538(class_757.java:499)
	... 16 more
Caused by: java.lang.IllegalArgumentException: The validated expression is false
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
	at net.minecraft.class_281.handler$bdg000$imm_ptl_core$onBeginCompileShaderInternal(class_281.java:540)
	at net.minecraft.class_281.method_34416(class_281.java)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:242)
	at net.minecraft.class_5944.<init>(class_5944.java:185)
	... 17 more

Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 462407976 bytes (440 MiB) / 1509949440 bytes (1440 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900KF
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: USB Mobile Monitor Virtual Display
	Graphics card #0 vendor: Amyuni
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.2.9
	Graphics card #1 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2208
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2225
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37445.30
	Virtual memory used (MB): 26947.15
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 491.34
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 6.0.1
		betterthirdperson: Better Third Person 1.9.0
		cem: Custom Entity Models 0.7.3_S10_1.19.4
			completeconfig-base: completeconfig-base 2.3.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.3.1
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		entity_model_features: Entity Model Features 0.2.4
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		immersive_portals: Immersive Portals 2.6.9
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.4
			imm_ptl_core: Immersive Portals Core 2.6.9
			q_misc_util: QMiscUtil 2.6.9
		iris: Iris 1.6.3
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.14.3
		malilib: MaLiLib 0.15.4
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		physicsmod: Physics Mod 2.12.3
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
		sodium: Sodium 0.4.10+build.24
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.1
		timetolive: Time To Live 0.5
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		travelerstitles: Traveler's Titles 1.19.4-Fabric-3.3.0
			org_reflections_reflections: reflections 0.10.2
		visuality: Visuality 0.7.0
		xaerominimapfair: Xaero's Minimap 23.4.0
		yet_another_config_lib: YetAnotherConfigLib 2.5.1+1.19.4
		yungsapi: YUNG's API 1.19.4-Fabric-3.10.1
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: rethinking-voxels_beta18d.zip
		Profile: MEDIUM (+2 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 522.25, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900KF

**Comment by haubna** [comment]
It seems like you are mixing 1.19.3 and 1.19.4 mods. Please make sure you have physics mod for 1.19.4.
