### ISSUE TITLE
(Physics mod pro) Crash with rubidium 7.0 & embeddium 1.10

### ISSUE THREAD

**Issue by Syclusion** [haubna/PhysicsMod#750]
Game crashes on forge when enabling dynamic block physics with embeddium / rubidium installed. Crash report attatched. Saw previous issue about lack of oculus support, that has since changed hence me posting a new report.

[crash-2023-09-27_23.44.23-client.txt](https://github.com/haubna/PhysicsMod/files/12745316/crash-2023-09-27_23.44.23-client.txt)

**Comment by AyakariRuka** [comment]
i got this crash 2
like:
java.lang.NoSuchMethodError: 'me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer me.jellysquid.mods.sodium.client.world.WorldRendererExtended.getSodiumWorldRenderer()'
	at net.diebuddies.compat.Sodium.scheduleChunkRebuild(Sodium.java:45) ~[physics-mod-pro-v160a-forge-1.20.1.jar%23309!/:3.0.8] {re:mixin,re:classloading}
	at net.minecraft.client.multiplayer.ClientChunkCache.chunkPosChanged(ClientChunkCache.java:1127) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.world.map.ClientChunkManagerMixin,pl:mixin:APP:physicsmod.mixins.json:vines.MixinClientChunkManager,pl:mixin:APP:flywheel.mixins.json:light.LightUpdateMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ClientChunkCacheMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.handler$bna000$render(GameRenderer.java:4694) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by haubna** [comment]
Thanks for the report, I have included a fix to make everything work with the latest oculus and rubidium with v160b. Please let me know if it works with embeddium.

**Comment by AyakariRuka** [comment]
thanks,it work with Sodium core!
