### ISSUE TITLE
Fractured physics causes crash on End Portal break [BUG]

### ISSUE THREAD

**Issue by JasonHorkles** [haubna/PhysicsMod#759]
**Describe the bug**
Breaking an End Portal block with the fractured physics particles causes the game to crash

**To Reproduce**
Set block break physics to fractured
Break an End Portal block

**Screenshots**
N/A

Minecraft Version: 1.20.1
Physics Mod Version: 3.0.9

**Crash Log**
```
java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:381)
	at net.diebuddies.physics.Mesh.calculatePBRData(Mesh.java:88)
	at net.diebuddies.physics.PhysicsMod.renderBlockIntoEntity(PhysicsMod.java:1065)
	at net.diebuddies.physics.PhysicsMod.renderBlockIntoEntity(PhysicsMod.java:1083)
	at net.diebuddies.render.PhysicsUpdater.updatePhysics(PhysicsUpdater.java:156)
	at net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:163)
	at net.minecraft.class_761.handler$cmb000$physicsmod$renderMain(class_761.java:10956)
	at net.minecraft.class_761.method_3251(class_761.java:13518)
	at net.minecraft.class_761.method_22710(class_761.java:1255)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by haubna** [comment]
Thanks for the report, will be fixed in the next version!
