### ISSUE TITLE
Crash when disassembling your boat

### ISSUE THREAD

**Issue by ShadowmeC3** [haubna/PhysicsMod#767]
The game crashes whenever you disassemble you valkyrien skies boat.

just disassemble your boat

uh ill just send the crash log:

 ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-10-24 19:11:03
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 24
	at net.minecraft.class_2791.method_38259(class_2791.java:162)
	at net.minecraft.class_2818.method_12010(class_2818.java:223)
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:51)
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:110)
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip$lambda$5(ShipAssembler.java:129)
	at org.valkyrienskies.core.impl.chunk_tracking.ShipActiveChunksSet.forEach(ShipActiveChunksSet.kt:49)
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip(ShipAssembler.java:109)
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.disassemble(ShipHelmBlockEntity.java:122)
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.tick(ShipHelmBlockEntity.java:90)
	at org.valkyrienskies.eureka.block.ShipHelmBlock.getTicker$lambda$1(ShipHelmBlock.java:139)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2791.method_38259(class_2791.java:162)
	at net.minecraft.class_2818.method_12010(class_2818.java:223)
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:51)
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:110)
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip$lambda$5(ShipAssembler.java:129)
	at org.valkyrienskies.core.impl.chunk_tracking.ShipActiveChunksSet.forEach(ShipActiveChunksSet.kt:49)
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip(ShipAssembler.java:109)
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.disassemble(ShipHelmBlockEntity.java:122)
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.tick(ShipHelmBlockEntity.java:90)
	at org.valkyrienskies.eureka.block.ShipHelmBlock.getTicker$lambda$1(ShipHelmBlock.java:139)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: vs_eureka:ship_helm // org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity
	Block: Block{vs_eureka:oak_ship_helm}[facing=east]
	Block location: World: (-28633079,67,12290060), Section: (at 9,3,12 in -1789568,4,768128; chunk contains blocks -28633088,-64,12290048 to -28633073,319,12290063), Region: (-55924,24004; contains chunks -1789568,768128 to -1789537,768159, blocks -28633088,-64,12290048 to -28632577,319,12290559)
	Block: Block{vs_eureka:oak_ship_helm}[facing=east]
	Block location: World: (-28633079,67,12290060), Section: (at 9,3,12 in -1789568,4,768128; chunk contains blocks -28633088,-64,12290048 to -28633073,319,12290063), Region: (-55924,24004; contains chunks -1789568,768128 to -1789537,768159, blocks -28633088,-64,12290048 to -28632577,319,12290559)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['ShadowMeC3'/134, l='ServerLevel[New World]', x=-560.46, y=65.54, z=1084.77]]
	Chunk stats: 6006
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 45833 game time, 45833 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 5425 (now: true), thunder time: 5425 (now: true)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 632946448 bytes (603 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4584
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0412
	Graphics card #1 versionInfo: DriverVersion=20.19.15.4531
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 25577.85
	Virtual memory used (MB): 16227.02
	Swap memory total (MB): 13456.00
	Swap memory used (MB): 425.64
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.90.4+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.24
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		physicsmod: Physics Mod 3.0.9
		sodium: Sodium 0.4.10+build.27
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.4
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		vs_eureka: VS Eureka Mod 1.3.0-beta.2
	Loaded Shaderpack: ComplementaryShaders_v4.7.2.zip
		Profile: LOW (+1 option changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['ShadowMeC3'/134, l='ServerLevel[New World]', x=-560.46, y=65.54, z=1084.77]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.24-1.20.1

Minecraft Version: 1.20.1
Physics Mod Version: v163-fabric

**Comment by haubna** [comment]
This is not a bug caused by physics mod. Please report it to the Valkyrien Skies 2 / Eureka devs.
