### ISSUE TITLE
Crash when breaking `light[waterlogged=true]` with Visible Barriers [BUG]

### ISSUE THREAD

**Issue by YoshiRulz** [haubna/PhysicsMod#813]
**Describe the bug**
Title. Visible Barriers adds a model for `minecraft:light`, toggleable with a keybind. When it's disabled, you can break a `light` in the usual way and it won't cause a crash.
```
java.lang.UnsupportedOperationException: No bounds for empty shape.
	at net.minecraft.class_265.method_1107(class_265.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.handler$zne000$physicsmod$crack(class_702.java:2190) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_3054(class_702.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1590(class_310.java:1798) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1993) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```
edit: This used to affect Visible Barriers alone, but it was fixed: see AmyMialeeMods/visiblebarriers#37.

**To Reproduce**
1. `/setblock ~ ~ ~ light[waterlogged=true]`
2. Enable Visible Barriers (defaults to B)
3. Punch `light`

Minecraft Version: 1.20.4
Physics Mod Version: 3.0.11
Also [Visible Barriers](https://modrinth.com/mod/visiblebarriers) 2.0.11 and Fabric API 0.95.1

**Comment by haubna** [comment]
Should be fixed with Pro v167. In case this error still happens please open up a new issue. Thanks for the report!
