### ISSUE TITLE
Linux aarch64 startup failure trying trying to load x64 `.so` [BUG]

### ISSUE THREAD

**Issue by bill88t** [haubna/PhysicsMod#843]
**Describe the bug**
When the mod is installed on a aarch64 (arm64) linux install, minecraft doesn't start.
The mod is attempting to load the x86_64 `.so` file.

rk3588 should be able to run this mod and I wanted to test it to see the performance difference.
If you need help retrieving / compiling a linked lib, lmk.

**Log**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'physicsmod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:224)
	at net.diebuddies.physics.ModExecutorClient.onInitializeClient(ModExecutorClient.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform LINUX
	at de.fabmax.physxjni.Loader.load(Loader.java:39)
	at physx.NativeObject.<clinit>(NativeObject.java:7)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/de.fabmax.physx-jni/2.2.2/libPhysXJniBindings_64.so: /tmp/de.fabmax.physx-jni/2.2.2/libPhysXJniBindings_64.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at de.fabmax.physxjni.NativeLib.load(NativeLib.java:49)
	at de.fabmax.physxjni.Loader.load(Loader.java:36)
	... 13 more
```

**Version info**
Minecraft Version: 1.20.4
Physics Mod Version: 3.0.13

**Comment by haubna** [comment]
Sorry but this operating system is currently not supported. I could try to included the android release of the PhysX library but I highly doubt that would work (https://github.com/fabmax/physx-jni/releases). I will only use the compiled libs from fabmax for security reasons.
