### ISSUE TITLE
Error occured during mod loading on Forge 1.19.4 with Optifine on Macbook Air M3

### ISSUE THREAD

**Issue by alessosussy** [haubna/PhysicsMod#974]
The message says the Physics mod failed to load correctly
java.lang.ExceptionInInitializerError: null
I am using the light version for 1.19.4 from the original website. At first I thought it could be the Optifine, or an interfering mod, but when running the physics mod by itself, the error still occurred. :/ 
Maybe it has to do with the Macbook M3, i am not very savvy with this stuff.
Here is the crashlog, with the mods I intend on using.
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2024-09-11 16:33:48
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.3.0-universal.jar%23228!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.3.0-universal.jar%23228!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:577) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:582) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:forge-DistantHorizons.forge.mixins.json:server.MixinUtilBackgroundThread,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:571) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:196) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1363) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:forge-DistantHorizons.forge.mixins.json:client.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1148) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:719) ~[client-1.19.4-20230314.122934-srg.jar%23223!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.3.0.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
-- MOD physicsmod --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:140) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading,re:mixin}
		at net.diebuddies.physics.ModExecutor.lambda$new$0(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
		at net.diebuddies.physics.ModExecutor.<init>(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.4-45.3.0.jar%23225!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.IllegalStateException: Failed loading native PhysX libraries for platform MACOS
		at de.fabmax.physxjni.Loader.load(Loader.java:38) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
		at physx.NativeObject.<clinit>(NativeObject.java:7) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:mixin,re:classloading}
		at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:140) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading,re:mixin}
		at net.diebuddies.physics.ModExecutor.lambda$new$0(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
		at net.diebuddies.physics.ModExecutor.<init>(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.4-45.3.0.jar%23225!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /Users/alessotheboss/Library/Application Support/minecraft/mods/physics-mod-2.12.5-mc-1.19.4-forge.jar
	Failure message: Physics Mod (physicsmod) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.12.5
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.UnsatisfiedLinkError: /private/var/folders/gx/3cmmjy117kj5bh5ggj5sjcgw0000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib: dlopen(/private/var/folders/gx/3cmmjy117kj5bh5ggj5sjcgw0000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib, 0x0001): tried: '/private/var/folders/gx/3cmmjy117kj5bh5ggj5sjcgw0000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/gx/3cmmjy117kj5bh5ggj5sjcgw0000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (no such file), '/private/var/folders/gx/3cmmjy117kj5bh5ggj5sjcgw0000gn/T/de.fabmax.physx-jni/1.1.0/libPhysXJniBindings_64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
Stacktrace:
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?] {}
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?] {}
	at java.lang.System.load(System.java:1953) ~[?:?] {re:mixin}
	at de.fabmax.physxjni.Loader.loadLibsFromResources(Loader.java:71) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
	at de.fabmax.physxjni.Loader.load(Loader.java:33) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
	at physx.NativeObject.<clinit>(NativeObject.java:7) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:mixin,re:classloading}
	at net.diebuddies.physics.StarterClient.onInitializeClient(StarterClient.java:140) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading,re:mixin}
	at net.diebuddies.physics.ModExecutor.lambda$new$0(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
	at net.diebuddies.physics.ModExecutor.<init>(ModExecutor.java:11) ~[physics-mod-2.12.5-mc-1.19.4-forge.jar%23209!/:2.12.5] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.4-45.3.0.jar%23225!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.4-45.3.0.jar%23224!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Mac OS X (aarch64) version 14.6.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 536603792 bytes (511 MiB) / 1073741824 bytes (1024 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M3
	Identifier: Apple Inc. Family 0xfa33415e Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M3
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 6184.28
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 615.13
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230623-173837
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: MakeUp-UltraFast-9.0a.zip
	OpenGlVersion: 4.1 Metal - 88.1
	OpenGlRenderer: Apple M3
	OpenGlVendor: Apple
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-3.0.1-mc1.19.4forge.jar               |Macaw's Bridges               |mcwbridges                    |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		grappling_hook_mod-1.19.4-1.19.4-v13.jar          |Grappling Hook Mod            |grapplemod                    |1.19.4-v13          |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDungeons-1.19.4-Forge-3.4.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.4-Forge-3.4.0  |COMMON_SET|Manifest: NOSIGNATURE
		BedBenefits-Forge-1.19.4-11.0.1.jar               |BedBenefits                   |bedbenefits                   |11.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.4-2.2.0.168.jar           |TerraBlender                  |terrablender                  |2.2.0.168           |COMMON_SET|Manifest: NOSIGNATURE
		physics-mod-2.12.5-mc-1.19.4-forge.jar            |Physics Mod                   |physicsmod                    |2.12.5              |ERROR     |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.18_mc1.19.4.jar          |Ambient Sounds                |ambientsounds                 |5.2.18              |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.19.4-Forge-2.3.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.4-Forge-2.3.0  |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.4-17.3.0.546.jar               |Biomes O' Plenty              |biomesoplenty                 |17.3.0.546          |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19.4-4.2.jar                     |GeckoLib 4                    |geckolib                      |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2+1.19.4.jar       |Player Animator               |playeranimator                |1.0.2+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.22_mc1.19.4.jar          |CreativeCore                  |creativecore                  |2.10.22             |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.4-Forge-2.3.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.4-Forge-2.3.0  |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.4-79.1-FORGE.jar                   |Patchouli                     |patchouli                     |1.19.4-79.1-FORGE   |COMMON_SET|Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.6.4_mc1.19.4.jar         |EnhancedVisuals               |enhancedvisuals               |1.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.3.4-1.19.4.jar                          |Citadel                       |citadel                       |2.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.3              |COMMON_SET|Manifest: NOSIGNATURE
		DiagonalFences-v6.0.0-1.19.4-Forge.jar            |Diagonal Fences               |diagonalfences                |6.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		YungsApi-1.19.4-Forge-3.10.1.jar                  |YUNG's API                    |yungsapi                      |1.19.4-Forge-3.10.1 |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.4-Forge-3.4.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.4-Forge-3.4.0  |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.4-18.0.6.jar                 |Bookshelf                     |bookshelf                     |18.0.6              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		make_bubbles_pop-0.3.0-forge-mc1.19.4-1.20.4.jar  |Make Bubbles Pop              |make_bubbles_pop              |0.3.0-forge         |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.4-Forge-2.4.0.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.4-Forge-2.4.0  |COMMON_SET|Manifest: NOSIGNATURE
		cave_dweller-1.19.4-1.6.1.jar                     |cave_dweller                  |cave_dweller                  |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-8.2.91-forge.jar                     |Architectury                  |architectury                  |8.2.91              |COMMON_SET|Manifest: NOSIGNATURE
		simplyswords-forge-1.43.1-1.19.3.jar              |Simply Swords                 |simplyswords                  |1.43.1-1.19.3       |COMMON_SET|Manifest: NOSIGNATURE
		immersivemc-1.4.1-1.19.4-forge.jar                |ImmersiveMC                   |immersivemc                   |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		DistantHorizons-2.2.1-a-1.19.4-forge-fabric.jar   |Distant Horizons              |distanthorizons               |2.2.1-a             |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v6.0.11-1.19.4-Forge.jar               |Puzzles Lib                   |puzzleslib                    |6.0.11              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		immersive_armors-1.5.6+1.19.4-forge.jar           |Immersive Armors              |immersive_armors              |1.5.6+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-10.1.117-forge.jar                   |Cloth Config v10 API          |cloth_config                  |10.1.117            |COMMON_SET|Manifest: NOSIGNATURE
		bettercombat-forge-1.7.1+1.19.4.jar               |Better Combat                 |bettercombat                  |1.7.1+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		combatroll-forge-1.1.5+1.19.4.jar                 |Combat Roll                   |combatroll                    |1.1.5+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.19.4-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.19.4-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.3.0-universal.jar                 |Forge                         |forge                         |45.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.19.4-4.2.1696-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1696            |COMMON_SET|Manifest: NOSIGNATURE
		deeper_oceans-1.19-v1-0.jar                       |Deeper Oceans                 |deeper_oceans                 |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.19.4-Forge-1.1.1.jar   |YUNG's Better Jungle Temples  |betterjungletemples           |1.19.4-Forge-1.1.1  |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: f3a3269a-4f01-4bce-9ff9-7d1e5c292f2c
	FML: 45.3
	Forge: net.minecraftforge:45.3.0

Minecraft Version: Forge release 1.19.4 version 45.3.0
Physics Mod Version: 2.12.5
<img width="849" alt="Screenshot 2024-09-11 at 4 49 42 PM" src="https://github.com/user-attachments/assets/02d2fdc0-9f63-4e74-bb19-8e63bba1396d">
Thank you

**Comment by Jacob0502** [comment]
Excuse me, has it been resolved?

**Comment by marcilenef907-cell** [comment]
#
