### ISSUE TITLE
Minecraft Crash 1.21 [BUG]

### ISSUE THREAD

**Issue by bohdan-prokopenko** [haubna/PhysicsMod#984]
**Describe the bug**
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-09-22 14:48:53
Description: Unexpected error

java.lang.AbstractMethodError: Receiver class net.diebuddies.compat.DummyVertexConsumerSodium does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatDescription)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboids(EntityRenderer.java:124)
	at me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.render(EntityRenderer.java:101)
	at net.minecraft.class_630.handler$bcp000$iris$onRender(class_630.java:1101)
	at net.minecraft.class_630.method_22699(class_630.java)
	at net.minecraft.class_4592.method_22949(class_4592.java:62)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_4592.method_2828(class_4592.java:62)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$bep000$physicsmod$onDeath(class_1309.java:5811)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_1429.method_5711(class_1429.java:252)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboids(EntityRenderer.java:124)
	at me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.render(EntityRenderer.java:101)
	at net.minecraft.class_630.handler$bcp000$iris$onRender(class_630.java:1101)
	at net.minecraft.class_630.method_22699(class_630.java)
	at net.minecraft.class_4592.method_22949(class_4592.java:62)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_4592.method_2828(class_4592.java:62)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:30)
	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:749)
	at net.minecraft.class_1309.handler$bep000$physicsmod$onDeath(class_1309.java:5811)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5711(class_1309.java:1875)
	at net.minecraft.class_1308.method_5711(class_1308.java:366)
	at net.minecraft.class_1429.method_5711(class_1429.java:252)
	at net.minecraft.class_634.method_11148(class_634.java:1082)
	at net.minecraft.class_2663.method_11471(class_2663.java:41)
	at net.minecraft.class_2663.method_11054(class_2663.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)

-- Uptime --
Details:
	JVM uptime: 248.692s
	Wall uptime: 234.841s
	High-res time: 233.367s
	Client ticks: 4525 ticks / 226.250s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SuetyKestrel936'/28, l='ClientLevel', x=43.21, y=67.00, z=25.50]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2102 game time, 2102 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 312

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, physicsmod, sodium

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 814970336 bytes (777 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4070 Ti SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 16376.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5585
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 512.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.24002.92
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 37849.90
	Virtual memory used (MiB): 21986.71
	Swap memory total (MiB): 5888.00
	Swap memory used (MiB): 95.88
	Space in storage for jna.tmpdir (MiB): available: 2270206.25, total: 3814561.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 2270206.25, total: 3814561.00
	Space in storage for io.netty.native.workdir (MiB): available: 2270206.25, total: 3814561.00
	Space in storage for java.io.tmpdir (MiB): available: 2270206.25, total: 3814561.00
	Space in storage for workdir (MiB): available: 2270206.25, total: 3814561.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		physicsmod: Physics Mod 3.0.20
		sodium: Sodium 0.5.11+mc1.21
	Loaded Shaderpack: (off) (fallback)
	Launched Version: fabric-loader-0.16.5-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4070 Ti SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.85, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, physicsmod, sodium
	Current Language: uk_ua
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 7800X3D 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SuetyKestrel936'/28, l='ServerLevel[Новий світ 1.21.0]', x=43.21, y=67.00, z=25.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -358064373035439864

**To Reproduce**
Destroy any block, or hit some mob

Minecraft Version: 1.21
Physics Mod Version: physics-mod-3.0.20-mc-1.21.0-fabric

**Comment by haubna** [comment]
Please upgrade to Iris 1.8.0-beta4 and Sodium 0.6.0-beta2
