### ISSUE TITLE
[compatibility] Forge 1.20.1 with Iris 1.80 alpha 4/sodium 0.60 alpha 3

### ISSUE THREAD

**Issue by nukularpower** [haubna/PhysicsMod#988]
Hello,

Iris and Sodium alphas now support Forge (and NeoForge) since at least Alpha 4, released on the Iris discord on 8/2/24.   However, cannot use the newest Physics mod release with these versions, it seems - get this error that seems related to Sodium:

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.diebuddies.compat.Sodium.disableWorkaround(Sodium.java:98) ~[physics-mod-pro-v171b-forge-1.20.1.jar%23134!/:3.0.14] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.VirtualScreen.handler$zlk000$newWindow(VirtualScreen.java:523) ~[client-1.20.1-20230612.114412-srg.jar%23136!/:?] {re:mixin,re:classloading,pl:mixin:APP:physicsmod.mixins.json:sodium.MixinWorkarounds,pl:mixin:A}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java) ~[client-1.20.1-20230612.114412-srg.jar%23136!/:?] {re:mixin,re:classloading,pl:mixin:APP:physicsmod.mixins.json:sodium.MixinWorkarounds,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23136!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}

Is there any fix or etc?  Hoping to use this while waiting on Create to update to 1.21.  Thanks to anyone with advice/help!

Minecraft Version: <version>
Physics Mod Version: <version>

**Comment by haubna** [comment]
The only fix is to switch to the Embeddium/Oculus version. I've listed the compatible ones here https://minecraftphysicsmod.com/installation
I hope this can help

**Comment by ShadowRocks2** [comment]
isnt iris/sodium fabric only?

**Comment by haubna** [comment]
They have an official NeoForge version. Embeedium/Oculus was a port for Forge (I think it is no longer being developed for Forge now but rather NeoForge).
